### ISSUE TITLE
Picklable Mekano

### ISSUE THREAD

**Issue by fgregg** [alad/Mekano#2]
It would be great if the mekano extension types were pickable. http://docs.python.org/2/library/pickle.html#pickling-and-unpickling-extension-types

I'd like to parallelize some code that uses mekano and `multiprocessing` requires that the objects be pickable.

**Comment by alad** [comment]
Aren't they already? I see **reduce** methods implemented in all classes, and CorpusStats even uses cpickle in its save function. Do you have some failing test code that uses pickle or multiprocessing on these extension types?

**Comment by fgregg** [comment]
This ended up being a path issue, everything nicely! Thanks @alad
